/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package memorygame.ui;

import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import memorygame.ArrayCardGenerator;
import memorygame.Card;
import memorygame.GenerateCardsException;

/**
 * Clase que crea la ventana del juego.
 *
 * @author Miguel Bastos Gándara.
 */
public class MemoryGame extends javax.swing.JFrame {

    private Card[][] cards;
    private JToggleButton[][] buttons;
    private Card lastSelectedCard;
    private JToggleButton lastSelectedButton;
    private int points;

    /**
     * Creates new form MemoryGame
     */
    public MemoryGame() {
        initComponents();
        buttons = new JToggleButton[][]{
            {jToggleButton00, jToggleButton01, jToggleButton02, jToggleButton03},
            {jToggleButton10, jToggleButton11, jToggleButton12, jToggleButton13},
            {jToggleButton20, jToggleButton21, jToggleButton22, jToggleButton23}
        };
        startNewGame(jComboBoxLevel.getSelectedIndex());
        this.setLocationRelativeTo(null);
    }

    private void startNewGame(int level) {
        ArrayCardGenerator cardGenerator = new ArrayCardGenerator();
        try {
            cards = cardGenerator.generateCards(level + 2, 4);

            for (int i = 0; i < buttons.length; i++) {
                for (JToggleButton button : buttons[i]) {
                    button.setText("");
                    button.setEnabled(true);
                    button.setSelected(false);
                    if (i == 2) {
                        button.setVisible(level != 0);
                    }
                }
            }
            lastSelectedCard = null;
            points = 100;
            showGameStatus();
        } catch (GenerateCardsException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showGameStatus() {
        jLblGameState.setText("Está jugando al nivel " + jComboBoxLevel.getSelectedItem() + " - Jugando por " + points + " puntos");
    }

    private void clearUnselectedButtons() {
        for (JToggleButton[] button : buttons) {
            for (JToggleButton button1 : button) {
                if (!button1.isSelected() && !button1.getText().isBlank()) {
                    button1.setText("");
                }
            }
        }
    }

    private void checkGameOver() {
        boolean check = true;
        for (Card[] card : cards) {
            for (Card card1 : card) {
                if (!card1.isHit()) {
                    check = false;
                }
            }
        }
        if (check) {
            JOptionPane.showMessageDialog(this, "¡Enhorabuena! Has acertado todas las cartas, consiguiendo " + points + " puntos.");
        }
    }

    private void uncover(int row, int column) {
        JToggleButton cardButton = buttons[row][column];
        Card card = cards[row][column];
        clearUnselectedButtons();
        cardButton.setText(card.getText());
        if (lastSelectedCard == null) {
            lastSelectedCard = card;
            lastSelectedButton = cardButton;
            cardButton.setEnabled(false);
        } else {
            if (card.isEquals(lastSelectedCard)) {
                card.setHit(true);
                lastSelectedCard.setHit(true);
                cardButton.setEnabled(false);
            } else {
                cardButton.setSelected(false);
                lastSelectedButton.setSelected(false);
                lastSelectedButton.setEnabled(true);
                points--;
                showGameStatus();
            }
            lastSelectedCard = null;
        }
        checkGameOver();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorth = new javax.swing.JPanel();
        jLblGameState = new javax.swing.JLabel();
        jPanelCenter = new javax.swing.JPanel();
        jToggleButton00 = new javax.swing.JToggleButton();
        jToggleButton01 = new javax.swing.JToggleButton();
        jToggleButton02 = new javax.swing.JToggleButton();
        jToggleButton03 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jPanelSouth = new javax.swing.JPanel();
        jLblLevel = new javax.swing.JLabel();
        jComboBoxLevel = new javax.swing.JComboBox<>();
        jBtnNewGame = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego de Memoria");
        setMaximumSize(new java.awt.Dimension(700, 529));
        setMinimumSize(new java.awt.Dimension(700, 529));
        setResizable(false);

        jPanelNorth.add(jLblGameState);

        getContentPane().add(jPanelNorth, java.awt.BorderLayout.NORTH);

        jPanelCenter.setLayout(new java.awt.GridLayout(3, 4));

        jToggleButton00.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton00.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton00.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton00ActionPerformed(evt);
            }
        });
        jPanelCenter.add(jToggleButton00);

        jToggleButton01.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton01.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton01.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton01ActionPerformed(evt);
            }
        });
        jPanelCenter.add(jToggleButton01);

        jToggleButton02.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton02.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton02.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton02ActionPerformed(evt);
            }
        });
        jPanelCenter.add(jToggleButton02);

        jToggleButton03.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton03.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton03.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton03ActionPerformed(evt);
            }
        });
        jPanelCenter.add(jToggleButton03);

        jToggleButton10.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton10.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton10.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed1(evt);
            }
        });
        jPanelCenter.add(jToggleButton10);

        jToggleButton11.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton11.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton11.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        jPanelCenter.add(jToggleButton11);

        jToggleButton12.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton12.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton12.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });
        jPanelCenter.add(jToggleButton12);

        jToggleButton13.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton13.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton13.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });
        jPanelCenter.add(jToggleButton13);

        jToggleButton20.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton20.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton20.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });
        jPanelCenter.add(jToggleButton20);

        jToggleButton21.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton21.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton21.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton21ActionPerformed(evt);
            }
        });
        jPanelCenter.add(jToggleButton21);

        jToggleButton22.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton22.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton22.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton22ActionPerformed(evt);
            }
        });
        jPanelCenter.add(jToggleButton22);

        jToggleButton23.setMaximumSize(new java.awt.Dimension(200, 200));
        jToggleButton23.setMinimumSize(new java.awt.Dimension(200, 200));
        jToggleButton23.setPreferredSize(new java.awt.Dimension(200, 200));
        jToggleButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton23ActionPerformed(evt);
            }
        });
        jPanelCenter.add(jToggleButton23);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jLblLevel.setText("Nivel:");
        jPanelSouth.add(jLblLevel);

        jComboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Medio", "Difícil" }));
        jPanelSouth.add(jComboBoxLevel);

        jBtnNewGame.setText("Nueva Partida");
        jBtnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNewGameActionPerformed(evt);
            }
        });
        jPanelSouth.add(jBtnNewGame);

        jBtnExit.setText("Salir");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        jPanelSouth.add(jBtnExit);

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNewGameActionPerformed
        startNewGame(jComboBoxLevel.getSelectedIndex());
    }//GEN-LAST:event_jBtnNewGameActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres salir?", "Salir", JOptionPane.YES_OPTION);
        if (option == 0 || option == -1) {
            this.dispose();
        }
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jToggleButton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton00ActionPerformed
        uncover(0, 0);
    }//GEN-LAST:event_jToggleButton00ActionPerformed

    private void jToggleButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton01ActionPerformed
        uncover(0, 1);
    }//GEN-LAST:event_jToggleButton01ActionPerformed

    private void jToggleButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton02ActionPerformed
        uncover(0, 2);
    }//GEN-LAST:event_jToggleButton02ActionPerformed

    private void jToggleButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton03ActionPerformed
        uncover(0, 3);
    }//GEN-LAST:event_jToggleButton03ActionPerformed

    private void jToggleButton10ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed1
        uncover(1, 0);
    }//GEN-LAST:event_jToggleButton10ActionPerformed1

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        uncover(1, 1);
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        uncover(1, 2);
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        uncover(1, 3);
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        uncover(2, 0);
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton21ActionPerformed
        uncover(2, 1);
    }//GEN-LAST:event_jToggleButton21ActionPerformed

    private void jToggleButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton22ActionPerformed
        uncover(2, 2);
    }//GEN-LAST:event_jToggleButton22ActionPerformed

    private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton23ActionPerformed
        uncover(2, 3);
    }//GEN-LAST:event_jToggleButton23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoryGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnNewGame;
    private javax.swing.JComboBox<String> jComboBoxLevel;
    private javax.swing.JLabel jLblGameState;
    private javax.swing.JLabel jLblLevel;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JToggleButton jToggleButton00;
    private javax.swing.JToggleButton jToggleButton01;
    private javax.swing.JToggleButton jToggleButton02;
    private javax.swing.JToggleButton jToggleButton03;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    // End of variables declaration//GEN-END:variables
}
